Updated the code to check for bzr, hg and svn directories.

diff --git a/aurupbot b/aurupbot
--- a/aurupbot
+++ b/aurupbot
@@ -80,7 +80,7 @@ generate_changelog() {
 
   if [[ $1 =~ -bzr$ ]]; then
     echo "==> Creating changelog from Bazaar revisions"
-    get_bzr_revs "${1%-bzr}"
+    get_bzr_revs "$1"
   elif [[ $1 =~ -git$ ]]; then
     echo "==> Creating changelog from Git commits"
     get_git_commits "$2/${1}_update.log"
@@ -94,8 +94,15 @@ generate_changelog() {
 }
 
 get_bzr_revs() {
+  BZR_DIR=$( grep -m 1 bzrdir PKGBUILD | cut -f 1 -d "=" --complement | tr -d \'\" )
+  [ -d "$BZR_DIR/.bzr" ] ||
+  BZR_DIR=${1%-bzr}
+  [ -d "$BZR_DIR/.bzr" ] ||
+  BZR_DIR=$1
+  [ -d "$BZR_DIR/.bzr" ] ||
+  echo "Couldn't find the directory." 2>&2
   FROM_REV=$(( ${OLD_PKGVER: 1} + 1 ))
-  REV_LOG=$( cd "$1" &&
+  REV_LOG=$( cd "$BZR_DIR" &&
              bzr log --log-format line -r $FROM_REV.. |
              sed -n "s/ .*[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} / /p" ) &&
   CHANGELOG=$( echo -e "\n\nChangelog\n=========\n$REV_LOG" )
@@ -119,7 +126,12 @@ get_git_commits() {
 
 get_hg_revs() {
   HG_DIR=$( grep -m 1 hgname PKGBUILD | cut -f 1 -d "=" --complement | tr -d \'\" )
-  [ "$HG_DIR" ] || HG_DIR=$1
+  [ -d "$HG_DIR/.hg" ] ||
+  HG_DIR=${1%-hg}
+  [ -d "$HG_DIR/.hg" ] ||
+  HG_DIR=$1
+  [ -d "$HG_DIR/.hg" ] ||
+  echo "Couldn't find the directory." 2>&2; return 1
   FROM_REV=$((${OLD_PKGVER: 1} + 1))
   REV_LOG=$( cd "$HG_DIR" &&
              hg log --template "{desc | firstline} ({node | short})\n" \
@@ -129,7 +141,12 @@ get_hg_revs() {
 
 get_svn_revs() {
   SVN_DIR=$( grep -m 1 svnname PKGBUILD | cut -f 1 -d "=" --complement | tr -d \'\" )
-  [ "$SVN_DIR" ] || HG_DIR=$1
+  [ -d "$SVN_DIR/.svn" ] ||
+  SVN_DIR=${1%-svn}
+  [ -d "$SVN_DIR/.svn" ] ||
+  SVN_DIR=$1
+  [ -d "$SVN_DIR/.svn" ] ||
+  echo "Couldn't find the directory." 2>&2; return 1
   FROM_REV=$((${OLD_PKGVER: 1} + 1))
   REV_LOG=$( cd "$SVN_DIR" &&
              svn log -r $FROM_REV:HEAD |
