Using printf instead of echo.

diff --git a/aurupbot b/aurupbot
--- a/aurupbot
+++ b/aurupbot
@@ -11,14 +11,14 @@
               ####################################################
 
 aur_check_update() {
-  echo "==> Checking for pkgver() function"
+  printf "==> Checking for pkgver() function\\n"
 
   grep -e "^[[:space:]]*pkgver[[:space:]]*([[:space:]]*)[[:space:]]*{" -i PKGBUILD \
   > /dev/null ||
-  { echo "No pkgver() function found." 2>&2
+  { printf "No pkgver() function found.\\n" 2>&2
     return 71; }
 
-  echo "==> Getting sources"
+  printf "==> Getting sources\\n"
 
   OLD_PKGVER=$( grep -m 1 "^[[:space:]]*pkgver" PKGBUILD |
                 cut -f 1 -d "=" --complement | tr -d \'\" )
@@ -30,19 +30,19 @@ aur_check_update() {
                 cut -f 1 -d "=" --complement | tr -d \'\" )
 
   if [ "$OLD_PKGVER" == "$NEW_PKGVER" ]; then
-    echo "$1 is up-to-date ($NEW_PKGVER)."
+    printf "$1 is up-to-date ($NEW_PKGVER).\\n"
     return 70
   else
-    echo "$1 is out-of-date ($OLD_PKGVER -> $NEW_PKGVER)."
+    printf "$1 is out-of-date ($OLD_PKGVER -> $NEW_PKGVER).\\n"
   fi
 }
 
 build_package() {
-  echo "==> Building package"
+  printf "==> Building package\\n"
   makepkg --force > "$2/${1}_makepkg.log" 2>&1 &&
   { NEW_PKGVER=$( grep -m 1 -e "^[[:space:]]*pkgver" PKGBUILD |
                   cut -f 1 -d "=" --complement | tr -d \'\" )
-    echo "Successfully built."; } ||
+    printf "Successfully built.\\n"; } ||
   { git reset --hard origin/master -q 2> /dev/null
     error_report "$1" "Build failed." "$2/${1}_makepkg.log" "critical"
     return 2; }
@@ -50,7 +50,7 @@ build_package() {
 
 check_namcap() {
   unset NAMCAP_E NAMCAP_W
-  echo "==> Checking package with namcap"
+  printf "==> Checking package with namcap\\n"
 
   PKGNAME=($( grep -m 1 -e "^[[:space:]]*pkgname" PKGBUILD |
               cut -f 1 -d "=" --complement | tr -d \'\"\(\) ))
@@ -73,7 +73,7 @@ check_namcap() {
 }
 
 error_report() {
-  echo "$2 See \"$3\" for details." 2>&2
+  printf "$2 See \"$3\" for details.\\n" 2>&2
   if [ "$ENABLE_NOTIFY" == true ]; then
     send_notification "$1" "$2 See \"$3\" for details." "$4"
   fi
@@ -88,25 +88,25 @@ generate_changelog() {
   if [[ $1 =~ -bzr$ ]] ||
      [[ $( cat "$2/${1}_update.log" | grep "^  -> .* bzr[ \.].*$" ) ]]
   then
-    echo "==> Creating changelog from Bazaar revisions"
+    printf "==> Creating changelog from Bazaar revisions\\n"
     get_clone_dir "$1" bzr &&
     get_bzr_revs "$1"
   elif [[ $1 =~ -git$ ]] ||
        [[ $( cat "$2/${1}_update.log" | grep "^  -> .* git[ \.].*$" ) ]]
   then
-    echo "==> Creating changelog from Git commits"
+    printf "==> Creating changelog from Git commits\\n"
     get_git_dir "$1" "$2/${1}_update.log" &&
     get_git_commits "$2/${1}_changelog.log"
   elif [[ $1 =~ -hg$ ]] ||
        [[ $( cat "$2/${1}_update.log" | grep "^  -> .* hg[ \.].*$" ) ]]
   then
-    echo "==> Creating changelog from Mercurial revisions"
+    printf "==> Creating changelog from Mercurial revisions\\n"
     get_clone_dir "$1" hg &&
     get_hg_revs "$1"
   elif [[ $1 =~ -svn$ ]] ||
        [[ $( cat "$2/${1}_update.log" | grep "^  -> .* svn[ \.].*$" ) ]]
   then
-    echo "==> Creating changelog from Subversion revisions"
+    printf "==> Creating changelog from Subversion revisions\\n"
     get_clone_dir "$1" svn &&
     get_svn_revs "$1"
   fi
@@ -119,7 +119,7 @@ get_clone_dir() {
   [ -d "$CLONE_DIR/.$2" ] ||
   CLONE_DIR=$1
   [ -d "$CLONE_DIR/.$2" ] ||
-  { echo "Couldn't find the $2 directory." 2>&2
+  { printf "Couldn't find the $2 directory.\\n" 2>&2
     return 1; }
 }
 
@@ -136,7 +136,7 @@ get_git_dir() {
   CLONE_DIR=$1
   [ -d "$CLONE_DIR" ] &&
   ( cd "$CLONE_DIR"; [ "$( git rev-parse --is-inside-git-dir )" == "true" ] ) ||
-  { echo "Couldn't find the Git directory." 2>&2
+  { printf "Couldn't find the Git directory.\\n" 2>&2
     return 1; }
 }
 
@@ -145,7 +145,7 @@ get_bzr_revs() {
   REV_LOG=$( cd "$CLONE_DIR" &&
              bzr log --log-format line -r $FROM_REV.. |
              sed -n "s/ .*[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} / /p" ) &&
-  CHANGELOG=$( echo -e "\n\nChangelog\n=========\n$REV_LOG" )
+  CHANGELOG=$( printf "\\n\\nChangelog\\n=========\\n$REV_LOG\\n" )
 }
 
 get_git_commits() {
@@ -165,7 +165,7 @@ get_git_commits() {
                     2> /dev/null
                   fi; } ) &&
   { cat <<< "$COMMIT_LOG" > "$1"
-    CHANGELOG=$( echo -e "\n\nChangelog\n=========\n$COMMIT_LOG" ); }
+    CHANGELOG=$( printf "\\n\\nChangelog\\n=========\\n$COMMIT_LOG\\n" ); }
 }
 
 get_hg_revs() {
@@ -173,7 +173,7 @@ get_hg_revs() {
   REV_LOG=$( cd "$CLONE_DIR" &&
              hg log --template "{desc | firstline} ({node | short})\n" \
                     -r $FROM_REV.. | tac ) &&
-  CHANGELOG=$( echo -e "\n\nChangelog\n=========\n$REV_LOG" )
+  CHANGELOG=$( printf "\\n\\nChangelog\\n=========\\n$REV_LOG\\n" )
 }
 
 get_svn_revs() {
@@ -184,28 +184,28 @@ get_svn_revs() {
              sed -n "/^r[0-9]* | .*$/{N;p}" |
              sed "s/^\(r[0-9]*\) | .*$/\1: /" |
              sed ":a;N;\$!ba;s/: \n/: /g" | tac ) &&
-  CHANGELOG=$( echo -e "\n\nChangelog\n=========\n$REV_LOG" )
+  CHANGELOG=$( printf "\\n\\nChangelog\\n=========\\n$REV_LOG\\n" )
 }
 
 get_user_packages() {
-  echo "==> Getting packages maintained by $1"
+  printf "==> Getting packages maintained by $1\\n"
 
   USER_PKGS=$( curl -s "https://aur.archlinux.org/rpc.php?type=msearch&arg=$1" |
                grep -Po '"Name":.*?[^\\],' |
                cut -f 4 -d \" )
 
   [ "$USER_PKGS" ] &&
-  echo $( wc -w <<< "$USER_PKGS" ) "package(s) found:" $USER_PKGS ||
-  echo "No package found." 2>&2
+  printf "$( wc -w <<< "$USER_PKGS" ) package(s) found:\\n$USER_PKGS\\n" ||
+  printf "No package found.\\n" 2>&2
 }
 
 send_email() {
-  echo "==> Sending email to $REPORT_EMAIL"
+  printf "==> Sending email to $REPORT_EMAIL\\n"
 
   hash mail 2> /dev/null &&
   { mail -a "$2" -s "The package $1 requires your attention" "$REPORT_EMAIL" <<< "$3" ||
     return 1; } ||
-  echo "The command mail was not found." 2>&2
+  printf "The command mail was not found.\\n" 2>&2
 }
 
 send_notification() {
@@ -223,11 +223,11 @@ send_notification() {
   hash notify-send 2> /dev/null &&
   { notify-send --urgency="$3" --icon="$ICON" --app-name="$SCRIPT_NAME" "$TITLE" "$2" ||
     return 1; } ||
-  echo "The command notify-send was not found." 2>&2
+  printf "The command notify-send was not found.\\n" 2>&2
 }
 
 update_aur() {
-  echo "==> Pushing new version to AUR"
+  printf "==> Pushing new version to AUR\\n"
 
   { git add PKGBUILD .SRCINFO 2>&1 | tee "$2/${1}_git.log" &&
     git commit -m "Updated version ($OLD_PKGVER -> $NEW_PKGVER).$CHANGELOG" \
@@ -310,7 +310,7 @@ while [ $# -gt 0 ]; do
     ENABLE_PUSH=false
     shift
   elif [[ $1 =~ ^- ]]; then
-    echo "`basename $0`: unrecognized option '$1'" >&2
+    printf "`basename $0`: unrecognized option '$1'\\n" >&2
     usage_guide
     exit 1
   else
@@ -339,7 +339,7 @@ for PKG in ${PKGS}; do
        [ -f "${SAVE_DIR}/$PKG/PKGBUILD" ]
     then
       cd "${SAVE_DIR}/$PKG"
-      echo "==> Updating the AUR repository for $PKG"
+      printf "==> Updating the AUR repository for $PKG\\n"
       git pull --quiet
       if [[ $( git diff origin/master ) ]]; then
         git diff origin/master > "${SAVE_DIR}/${PKG}_diff.log"
@@ -351,7 +351,7 @@ for PKG in ${PKGS}; do
       [ -e "${SAVE_DIR}/$PKG" ] &&
       { rm -rf "${SAVE_DIR}/$PKG" ||
         exit 3; }
-      echo "==> Cloning the AUR repository for $PKG"
+      printf "==> Cloning the AUR repository for $PKG\\n"
       git clone "ssh://aur@aur.archlinux.org/$PKG.git" "${SAVE_DIR}/$PKG" --quiet
     fi
   } &&
@@ -369,7 +369,7 @@ for PKG in ${PKGS}; do
           send_notification "$PKG" "The package was updated and uploaded to AUR." "low"
         fi
       else
-        echo -e "\nThe package was updated in \"$SAVE_DIR/$PKG\"."
+        printf "\\nThe package was updated in \"$SAVE_DIR/$PKG\".\\n"
         if [ "$ENABLE_NOTIFY" == true ]; then
           send_notification "$PKG" "The package was updated in \"$SAVE_DIR/$PKG\"." "low"
         fi
